"""empty message

Revision ID: 5f6b7fa884be
Revises: 
Create Date: 2017-09-27 15:57:08.082236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6b7fa884be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_status', sa.Text(), nullable=True),
    sa.Column('niche_size', sa.Integer(), nullable=True),
    sa.Column('optimum_change_speed', sa.REAL(), nullable=True),
    sa.Column('selection_radius', sa.REAL(), nullable=True),
    sa.Column('number_of_generations', sa.Integer(), nullable=True),
    sa.Column('number_of_traits', sa.Integer(), nullable=True),
    sa.Column('random_mutation_rate', sa.REAL(), nullable=True),
    sa.Column('TE_starting_te_no', sa.Integer(), nullable=True),
    sa.Column('TE_deauton_probability', sa.REAL(), nullable=True),
    sa.Column('TE_inactivation_probability', sa.REAL(), nullable=True),
    sa.Column('TE_transposition_rate', sa.REAL(), nullable=True),
    sa.Column('TE_deletion_probability', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
