"""empty message

Revision ID: a7bbd4a157fc
Revises: 
Create Date: 2017-09-25 18:36:52.451608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bbd4a157fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_size', sa.Integer(), nullable=True),
    sa.Column('number_of_traits', sa.Integer(), nullable=True),
    sa.Column('optimum_change_speed', sa.REAL(), nullable=True),
    sa.Column('simulation_status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
